//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_Cyca_Admission_Discharge_Reason
    {
        public apl_Cyca_Admission_Discharge_Reason()
        {
            this.CYCA_Admissions_Discharge = new HashSet<CYCA_Admissions_Discharge>();
        }
    
        public int DischargeReasonId { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<CYCA_Admissions_Discharge> CYCA_Admissions_Discharge { get; set; }
    }
}
