//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_Admission_Type
    {
        public apl_Admission_Type()
        {
            this.CYCA_Admissions_AdmissionDetails = new HashSet<CYCA_Admissions_AdmissionDetails>();
            this.CYCA_ReAdmissionDetails = new HashSet<CYCA_ReAdmissionDetails>();
        }
    
        public int Admission_Type_Id { get; set; }
        public string Description { get; set; }
        public string Defination { get; set; }
        public string Source { get; set; }
    
        public virtual ICollection<CYCA_Admissions_AdmissionDetails> CYCA_Admissions_AdmissionDetails { get; set; }
        public virtual ICollection<CYCA_ReAdmissionDetails> CYCA_ReAdmissionDetails { get; set; }
    }
}
