//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_Cyca_Facility
    {
        public apl_Cyca_Facility()
        {
            this.apl_Cyca_Venue = new HashSet<apl_Cyca_Venue>();
            this.apl_Employee = new HashSet<Employee>();
            this.CYCA_Admissions_AdmissionDetails = new HashSet<CYCA_Admissions_AdmissionDetails>();
            this.CYCA_ReAdmissionDetails = new HashSet<CYCA_ReAdmissionDetails>();
            this.CYCA_PersonalAndFacilityInventory = new HashSet<CYCA_PersonalAndFacilityInventory>();
        }
    
        public int Facility_Id { get; set; }
        public string FacilityName { get; set; }
        public string OfficialCapacity { get; set; }
        public string FacilityAddress { get; set; }
        public string FacilityFaxNo { get; set; }
        public string FacilityEmailAddress { get; set; }
        public string FacilityTelNo { get; set; }
        public string FacilityAccro { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public Nullable<int> Admission_Type_Id { get; set; }
        public Nullable<int> Organization_Id { get; set; }
    
        public virtual ICollection<apl_Cyca_Venue> apl_Cyca_Venue { get; set; }
        public virtual ICollection<Employee> apl_Employee { get; set; }
        public virtual ICollection<CYCA_Admissions_AdmissionDetails> CYCA_Admissions_AdmissionDetails { get; set; }
        public virtual ICollection<CYCA_ReAdmissionDetails> CYCA_ReAdmissionDetails { get; set; }
        public virtual ICollection<CYCA_PersonalAndFacilityInventory> CYCA_PersonalAndFacilityInventory { get; set; }
    }
}
