//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_Cyca_Appointment_Type
    {
        public apl_Cyca_Appointment_Type()
        {
            this.CYCA_Appointment = new HashSet<CYCA_Appointment>();
        }
    
        public int AppointmentTypeId { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
        public int AppointmentCategoryId { get; set; }
    
        public virtual apl_Cyca_Appointment_Category apl_Cyca_Appointment_Category { get; set; }
        public virtual ICollection<CYCA_Appointment> CYCA_Appointment { get; set; }
    }
}
