//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCA_ReAdmissionDetails
    {
        public CYCA_ReAdmissionDetails()
        {
            this.CYCA_Admissions_Document = new HashSet<CYCA_Admissions_Document>();
            this.CYCA_Admissions_GangMembership = new HashSet<CYCA_Admissions_GangMembership>();
            this.CYCA_Tatoos = new HashSet<CYCA_Tatoos>();
        }
    
        public int ReAdmission_Id { get; set; }
        public int Admission_Id { get; set; }
        public int Client_Id { get; set; }
        public Nullable<System.DateTime> Case_Start_Date { get; set; }
        public string Case_Start_Time { get; set; }
        public Nullable<System.DateTime> Case_End_Date { get; set; }
        public Nullable<System.DateTime> Case_End_Time { get; set; }
        public int Facility_Id { get; set; }
        public Nullable<int> Admission_Type_Id { get; set; }
        public string Comments_And_Observation { get; set; }
        public Nullable<int> Venue_Id { get; set; }
        public string Additional_Info { get; set; }
        public Nullable<System.DateTime> Admission_Date { get; set; }
        public Nullable<System.DateTime> Date_Captured { get; set; }
        public Nullable<int> Captured_By { get; set; }
        public Nullable<int> Pcm_Ass_No { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public string Client_Module_Id { get; set; }
        public Nullable<int> Document_Type_Id { get; set; }
        public string OtherDocTypeDescription { get; set; }
        public string OtherGangMemberDescription { get; set; }
    
        public virtual apl_Admission_Type apl_Admission_Type { get; set; }
        public virtual apl_Cyca_Facility apl_Cyca_Facility { get; set; }
        public virtual apl_Cyca_Venue apl_Cyca_Venue { get; set; }
        public virtual User apl_User { get; set; }
        public virtual CYCA_Admissions_AdmissionDetails CYCA_Admissions_AdmissionDetails { get; set; }
        public virtual ICollection<CYCA_Admissions_Document> CYCA_Admissions_Document { get; set; }
        public virtual Client int_Client { get; set; }
        public virtual int_Client_Module_Registration int_Client_Module_Registration { get; set; }
        public virtual ICollection<CYCA_Admissions_GangMembership> CYCA_Admissions_GangMembership { get; set; }
        public virtual ICollection<CYCA_Tatoos> CYCA_Tatoos { get; set; }
    }
}
