//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCA_Admissions_IllegalItemsFound
    {
        public CYCA_Admissions_IllegalItemsFound()
        {
            this.CYCA_IllegalItems_Document = new HashSet<CYCA_IllegalItems_Document>();
        }
    
        public int Item_Found_Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Handed_By { get; set; }
        public Nullable<int> Person_Id { get; set; }
        public Nullable<int> Admission_Id { get; set; }
        public Nullable<int> Document_Type_Id { get; set; }
        public Nullable<System.DateTime> Date_Captured { get; set; }
        public Nullable<int> Captured_By { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public string OtherDocTypeDescription { get; set; }
    
        public virtual apl_Cyca_Admission_DocumentType apl_Cyca_Admission_DocumentType { get; set; }
        public virtual User apl_User { get; set; }
        public virtual CYCA_Admissions_AdmissionDetails CYCA_Admissions_AdmissionDetails { get; set; }
        public virtual Person int_Person { get; set; }
        public virtual ICollection<CYCA_IllegalItems_Document> CYCA_IllegalItems_Document { get; set; }
    }
}
