//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCA_Dynamic_Form
    {
        public CYCA_Dynamic_Form()
        {
            this.CYCA_Dynamic_Form_Data = new HashSet<CYCA_Dynamic_Form_Data>();
        }
    
        public int Dynamic_Form_Id { get; set; }
        public int Dynamic_Form_Type_Id { get; set; }
        public int Version { get; set; }
        public bool Is_Active { get; set; }
        public string Definition { get; set; }
        public string SummaryDefinition { get; set; }
    
        public virtual CYCA_Dynamic_Form_Type CYCA_Dynamic_Form_Type { get; set; }
        public virtual ICollection<CYCA_Dynamic_Form_Data> CYCA_Dynamic_Form_Data { get; set; }
    }
}
