//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCA_Child_Allocation
    {
        public int Child_Allocation_Id { get; set; }
        public Nullable<int> Admission_Id { get; set; }
        public Nullable<int> Person_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<int> Sent_By { get; set; }
        public Nullable<System.DateTime> Date_Allocated { get; set; }
        public Nullable<System.DateTime> Date_Transferred { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual User apl_User { get; set; }
        public virtual Person int_Person { get; set; }
        public virtual CYCA_Admissions_AdmissionDetails CYCA_Admissions_AdmissionDetails { get; set; }
    }
}
