//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCA_Child_Movement
    {
        public int Movement_Id { get; set; }
        public Nullable<int> Person_Id { get; set; }
        public Nullable<int> Admission_Id { get; set; }
        public Nullable<int> Venue_Id { get; set; }
        public Nullable<System.DateTime> Date_Moved { get; set; }
        public Nullable<System.DateTime> Time_Moved { get; set; }
        public Nullable<int> Moved_By { get; set; }
        public Nullable<System.DateTime> Check_Out_Date { get; set; }
        public Nullable<System.DateTime> Check_Out_Time { get; set; }
        public Nullable<System.DateTime> Child_Check_Out_Date { get; set; }
        public Nullable<System.DateTime> Child_Check_Out_Time { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual apl_Cyca_Venue apl_Cyca_Venue { get; set; }
        public virtual User apl_User { get; set; }
        public virtual Person int_Person { get; set; }
        public virtual CYCA_Admissions_AdmissionDetails CYCA_Admissions_AdmissionDetails { get; set; }
    }
}
