//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCA_Appointment
    {
        public int ChildAppointmentID { get; set; }
        public int AdmissionID { get; set; }
        public System.DateTime AppointmentStartDate { get; set; }
        public System.DateTime AppointmentEndDate { get; set; }
        public string Duration { get; set; }
        public int DurationMinutes { get; set; }
        public int AppointmentTypeID { get; set; }
        public int AppointmentCatergoryId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime DateCaptured { get; set; }
    
        public virtual apl_Cyca_Appointment_Category apl_Cyca_Appointment_Category { get; set; }
        public virtual apl_Cyca_Appointment_Type apl_Cyca_Appointment_Type { get; set; }
        public virtual CYCA_Admissions_AdmissionDetails CYCA_Admissions_AdmissionDetails { get; set; }
    }
}
