//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCA_Admissions_Discharge
    {
        public CYCA_Admissions_Discharge()
        {
            this.CYCA_Admissions_Document = new HashSet<CYCA_Admissions_Document>();
        }
    
        public int DischargeId { get; set; }
        public int AdmissionId { get; set; }
        public int UserId { get; set; }
        public int UserHandedOverId { get; set; }
        public string PersonReceivingName { get; set; }
        public int OgranizationId { get; set; }
        public int PersonReceivingDesignationId { get; set; }
        public int DischargeReasonId { get; set; }
        public System.DateTime DischargeDate { get; set; }
        public bool KeepBedSpace { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Comments { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<int> DocType_Id { get; set; }
        public string OtherOrgComment { get; set; }
    
        public virtual apl_Cyca_Admission_Discharge_Reason apl_Cyca_Admission_Discharge_Reason { get; set; }
        public virtual User apl_User { get; set; }
        public virtual User apl_User1 { get; set; }
        public virtual ICollection<CYCA_Admissions_Document> CYCA_Admissions_Document { get; set; }
        public virtual CYCA_Admissions_AdmissionDetails CYCA_Admissions_AdmissionDetails { get; set; }
    }
}
