//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCA_PersonalAndFacilityInventory
    {
        public int Inventory_Id { get; set; }
        public int Person_Id { get; set; }
        public int Facility_Id { get; set; }
        public int Admission_Id { get; set; }
        public int Inventory_Type_Id { get; set; }
        public string Item_Type { get; set; }
        public string Item_Color { get; set; }
        public int Item_Quantity { get; set; }
        public string Item_Description { get; set; }
        public System.DateTime Date_Handed_In { get; set; }
        public int Item_Handed_By { get; set; }
        public int Item_Handed_To { get; set; }
        public Nullable<int> Return_Status_Id { get; set; }
        public Nullable<System.DateTime> Date_Returned { get; set; }
        public Nullable<int> Quantity_Returned { get; set; }
        public Nullable<int> Returned_By { get; set; }
        public string Reason_Not_Returned { get; set; }
        public System.DateTime Date_Created { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual apl_Cyca_Facility apl_Cyca_Facility { get; set; }
        public virtual apl_Cyca_Inventory_Return_Status apl_Cyca_Inventory_Return_Status { get; set; }
        public virtual apl_Cyca_Inventory_Type apl_Cyca_Inventory_Type { get; set; }
        public virtual User apl_User { get; set; }
        public virtual User apl_User1 { get; set; }
        public virtual CYCA_Admissions_AdmissionDetails CYCA_Admissions_AdmissionDetails { get; set; }
        public virtual Person int_Person { get; set; }
    }
}
