//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCA_Admissions_ReAdmissionDetails
    {
        public int Re_Admission_Id { get; set; }
        public Nullable<int> Admission_Id { get; set; }
        public string Re_Admission_StartDate { get; set; }
        public Nullable<System.DateTime> Re_Admission_CaseEndDate { get; set; }
        public Nullable<int> AdmissionType_Id { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Date_Captured { get; set; }
        public Nullable<int> Re_Admission_VenueId { get; set; }
        public Nullable<System.DateTime> Re_Admission_CourtStartTime { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual apl_Cyca_Venue apl_Cyca_Venue { get; set; }
        public virtual CYCA_Admissions_AdmissionDetails CYCA_Admissions_AdmissionDetails { get; set; }
    }
}
