//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCA_Admissions_AdmissionDetails
    {
        public CYCA_Admissions_AdmissionDetails()
        {
            this.CYCA_Admissions_Document = new HashSet<CYCA_Admissions_Document>();
            this.CYCA_Admissions_AdmissionDocument = new HashSet<CYCA_Admissions_AdmissionDocument>();
            this.CYCA_Admissions_BodilySearch = new HashSet<CYCA_Admissions_BodilySearch>();
            this.CYCA_Admissions_Discharge = new HashSet<CYCA_Admissions_Discharge>();
            this.CYCA_Admissions_ExtraMuralActivity = new HashSet<CYCA_Admissions_ExtraMuralActivity>();
            this.CYCA_Admissions_ReAdmissionDetails = new HashSet<CYCA_Admissions_ReAdmissionDetails>();
            this.CYCA_Appointment = new HashSet<CYCA_Appointment>();
            this.CYCA_BodilySearch_Document = new HashSet<CYCA_BodilySearch_Document>();
            this.CYCA_Child_Allocation = new HashSet<CYCA_Child_Allocation>();
            this.CYCA_Child_Movement = new HashSet<CYCA_Child_Movement>();
            this.CYCA_Child_Transfer = new HashSet<CYCA_Child_Transfer>();
            this.CYCA_IllegalItems_Document = new HashSet<CYCA_IllegalItems_Document>();
            this.CYCA_ReAdmissionDetails = new HashSet<CYCA_ReAdmissionDetails>();
            this.CYCA_Admissions_IllegalItemsFound = new HashSet<CYCA_Admissions_IllegalItemsFound>();
            this.CYCA_BodilySearch = new HashSet<CYCA_BodilySearch>();
            this.CYCA_GangAndTatooDocument = new HashSet<CYCA_GangAndTatooDocument>();
            this.CYCA_Admissions_GangMembership = new HashSet<CYCA_Admissions_GangMembership>();
            this.CYCA_Tatoos = new HashSet<CYCA_Tatoos>();
            this.CYCA_PersonalAndFacilityInventory = new HashSet<CYCA_PersonalAndFacilityInventory>();
        }
    
        public int Admission_Id { get; set; }
        public int Client_Id { get; set; }
        public Nullable<System.DateTime> Case_Start_Date { get; set; }
        public string Case_Start_Time { get; set; }
        public Nullable<System.DateTime> Case_End_Date { get; set; }
        public Nullable<System.DateTime> Case_End_Time { get; set; }
        public int Facility_Id { get; set; }
        public Nullable<int> Admission_Type_Id { get; set; }
        public string Comments_And_Observation { get; set; }
        public Nullable<int> Venue_Id { get; set; }
        public Nullable<System.DateTime> Admission_Date { get; set; }
        public Nullable<System.DateTime> Date_Captured { get; set; }
        public Nullable<int> Captured_By { get; set; }
        public Nullable<int> Pcm_Ass_No { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public string Client_Module_Id { get; set; }
        public Nullable<int> Document_Type_Id { get; set; }
        public string OtherDocTypeDescription { get; set; }
        public string OtherGangMemberDescription { get; set; }
    
        public virtual apl_Admission_Type apl_Admission_Type { get; set; }
        public virtual apl_Cyca_Facility apl_Cyca_Facility { get; set; }
        public virtual apl_Cyca_Venue apl_Cyca_Venue { get; set; }
        public virtual User apl_User { get; set; }
        public virtual ICollection<CYCA_Admissions_Document> CYCA_Admissions_Document { get; set; }
        public virtual Client int_Client { get; set; }
        public virtual int_Client_Module_Registration int_Client_Module_Registration { get; set; }
        public virtual ICollection<CYCA_Admissions_AdmissionDocument> CYCA_Admissions_AdmissionDocument { get; set; }
        public virtual ICollection<CYCA_Admissions_BodilySearch> CYCA_Admissions_BodilySearch { get; set; }
        public virtual ICollection<CYCA_Admissions_Discharge> CYCA_Admissions_Discharge { get; set; }
        public virtual ICollection<CYCA_Admissions_ExtraMuralActivity> CYCA_Admissions_ExtraMuralActivity { get; set; }
        public virtual ICollection<CYCA_Admissions_ReAdmissionDetails> CYCA_Admissions_ReAdmissionDetails { get; set; }
        public virtual ICollection<CYCA_Appointment> CYCA_Appointment { get; set; }
        public virtual ICollection<CYCA_BodilySearch_Document> CYCA_BodilySearch_Document { get; set; }
        public virtual ICollection<CYCA_Child_Allocation> CYCA_Child_Allocation { get; set; }
        public virtual ICollection<CYCA_Child_Movement> CYCA_Child_Movement { get; set; }
        public virtual ICollection<CYCA_Child_Transfer> CYCA_Child_Transfer { get; set; }
        public virtual ICollection<CYCA_IllegalItems_Document> CYCA_IllegalItems_Document { get; set; }
        public virtual ICollection<CYCA_ReAdmissionDetails> CYCA_ReAdmissionDetails { get; set; }
        public virtual ICollection<CYCA_Admissions_IllegalItemsFound> CYCA_Admissions_IllegalItemsFound { get; set; }
        public virtual ICollection<CYCA_BodilySearch> CYCA_BodilySearch { get; set; }
        public virtual ICollection<CYCA_GangAndTatooDocument> CYCA_GangAndTatooDocument { get; set; }
        public virtual ICollection<CYCA_Admissions_GangMembership> CYCA_Admissions_GangMembership { get; set; }
        public virtual ICollection<CYCA_Tatoos> CYCA_Tatoos { get; set; }
        public virtual ICollection<CYCA_PersonalAndFacilityInventory> CYCA_PersonalAndFacilityInventory { get; set; }
    }
}
