//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCA_Tatoos
    {
        public int Tatoo_Id { get; set; }
        public Nullable<int> Admission_Id { get; set; }
        public bool Tatoo_Visible { get; set; }
        public string Tatoo_Description { get; set; }
        public string Tatoo_Size { get; set; }
        public string Tatoo_Position { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Date_Captured { get; set; }
        public Nullable<int> ReAdmission_Id { get; set; }
        public Nullable<int> Document_Type_Id { get; set; }
        public string OtherDocTypeDescription { get; set; }
        public string OtherGangMemberDescription { get; set; }
    
        public virtual CYCA_Admissions_AdmissionDetails CYCA_Admissions_AdmissionDetails { get; set; }
        public virtual CYCA_ReAdmissionDetails CYCA_ReAdmissionDetails { get; set; }
    }
}
