//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_DSD_Afis
    {
        public int int_DSDAfis { get; set; }
        public int Person_Id { get; set; }
        public System.Guid Uid { get; set; }
        public bool Is_Verified { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
    
        public virtual Person int_Person { get; set; }
    }
}
