//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_HBS_Condition
    {
        public int Condition_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public string School_Attendance { get; set; }
        public string Family_Time { get; set; }
        public string Good_Behaviour { get; set; }
        public string Peer_Association { get; set; }
        public string Reporting { get; set; }
        public string Supervision { get; set; }
    }
}
