//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Employees = new HashSet<Employee>();
            this.Groups = new HashSet<Group>();
            this.Roles = new HashSet<Role>();
            this.Users_Delegated_From = new HashSet<User_Role_Delegation>();
            this.Users_Delegated_To = new HashSet<User_Role_Delegation>();
            this.Case_Manager_Supervisor_Intake_Assessments = new HashSet<Intake_Assessment>();
            this.Case_Manager_Intake_Assessments = new HashSet<Intake_Assessment>();
            this.Assessor_Intake_Assessments = new HashSet<Intake_Assessment>();
            this.NISIS_Profiling_Instances = new HashSet<Profiling_Instance>();
            this.ACM_ChildrensCourtReport = new HashSet<ACM_ChildrensCourtReport>();
            this.NISIS_Community_Profiling_Instance = new HashSet<Community_Profiling_Instance>();
            this.CPR_Correspondence = new HashSet<CPR_Correspondence>();
            this.apl_Social_Worker = new HashSet<Social_Worker>();
            this.CYCA_Child_Allocation_And_Transfer_Date = new HashSet<CYCA_Child_Allocation_And_Transfer_Date>();
            this.CYCA_Team_Allocation = new HashSet<CYCA_Team_Allocation>();
            this.CYCA_Dynamic_Form_Data = new HashSet<CYCA_Dynamic_Form_Data>();
            this.CYCA_Admissions_BodilySearch = new HashSet<CYCA_Admissions_BodilySearch>();
            this.CYCA_Admissions_BodilySearch1 = new HashSet<CYCA_Admissions_BodilySearch>();
            this.CYCA_Child_Movement = new HashSet<CYCA_Child_Movement>();
            this.CYCA_Child_Allocation = new HashSet<CYCA_Child_Allocation>();
            this.CYCA_Child_Transfer = new HashSet<CYCA_Child_Transfer>();
            this.CYCA_Admissions_Discharge = new HashSet<CYCA_Admissions_Discharge>();
            this.CYCA_Admissions_Discharge1 = new HashSet<CYCA_Admissions_Discharge>();
            this.CYCA_Admissions_AdmissionDetails = new HashSet<CYCA_Admissions_AdmissionDetails>();
            this.CYCA_ReAdmissionDetails = new HashSet<CYCA_ReAdmissionDetails>();
            this.CYCA_Admissions_IllegalItemsFound = new HashSet<CYCA_Admissions_IllegalItemsFound>();
            this.CYCA_BodilySearch = new HashSet<CYCA_BodilySearch>();
            this.CYCA_BodilySearch1 = new HashSet<CYCA_BodilySearch>();
            this.CYCA_PersonalAndFacilityInventory = new HashSet<CYCA_PersonalAndFacilityInventory>();
            this.CYCA_PersonalAndFacilityInventory1 = new HashSet<CYCA_PersonalAndFacilityInventory>();
            this.apl_User_Image = new HashSet<apl_User_Image>();
        }
    
        public int User_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Initials { get; set; }
        public string Email_Address { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Date_Last_Login { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<User_Role_Delegation> Users_Delegated_From { get; set; }
        public virtual ICollection<User_Role_Delegation> Users_Delegated_To { get; set; }
        public virtual ICollection<Intake_Assessment> Case_Manager_Supervisor_Intake_Assessments { get; set; }
        public virtual ICollection<Intake_Assessment> Case_Manager_Intake_Assessments { get; set; }
        public virtual ICollection<Intake_Assessment> Assessor_Intake_Assessments { get; set; }
        public virtual ICollection<Profiling_Instance> NISIS_Profiling_Instances { get; set; }
        public virtual ICollection<ACM_ChildrensCourtReport> ACM_ChildrensCourtReport { get; set; }
        public virtual ICollection<Community_Profiling_Instance> NISIS_Community_Profiling_Instance { get; set; }
        public virtual ICollection<CPR_Correspondence> CPR_Correspondence { get; set; }
        public virtual ICollection<Social_Worker> apl_Social_Worker { get; set; }
        public virtual ICollection<CYCA_Child_Allocation_And_Transfer_Date> CYCA_Child_Allocation_And_Transfer_Date { get; set; }
        public virtual ICollection<CYCA_Team_Allocation> CYCA_Team_Allocation { get; set; }
        public virtual ICollection<CYCA_Dynamic_Form_Data> CYCA_Dynamic_Form_Data { get; set; }
        public virtual ICollection<CYCA_Admissions_BodilySearch> CYCA_Admissions_BodilySearch { get; set; }
        public virtual ICollection<CYCA_Admissions_BodilySearch> CYCA_Admissions_BodilySearch1 { get; set; }
        public virtual ICollection<CYCA_Child_Movement> CYCA_Child_Movement { get; set; }
        public virtual ICollection<CYCA_Child_Allocation> CYCA_Child_Allocation { get; set; }
        public virtual ICollection<CYCA_Child_Transfer> CYCA_Child_Transfer { get; set; }
        public virtual ICollection<CYCA_Admissions_Discharge> CYCA_Admissions_Discharge { get; set; }
        public virtual ICollection<CYCA_Admissions_Discharge> CYCA_Admissions_Discharge1 { get; set; }
        public virtual ICollection<CYCA_Admissions_AdmissionDetails> CYCA_Admissions_AdmissionDetails { get; set; }
        public virtual ICollection<CYCA_ReAdmissionDetails> CYCA_ReAdmissionDetails { get; set; }
        public virtual ICollection<CYCA_Admissions_IllegalItemsFound> CYCA_Admissions_IllegalItemsFound { get; set; }
        public virtual ICollection<CYCA_BodilySearch> CYCA_BodilySearch { get; set; }
        public virtual ICollection<CYCA_BodilySearch> CYCA_BodilySearch1 { get; set; }
        public virtual ICollection<CYCA_PersonalAndFacilityInventory> CYCA_PersonalAndFacilityInventory { get; set; }
        public virtual ICollection<CYCA_PersonalAndFacilityInventory> CYCA_PersonalAndFacilityInventory1 { get; set; }
        public virtual ICollection<apl_User_Image> apl_User_Image { get; set; }
    }
}
