//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDIIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Areas = new HashSet<Area>();
            this.Paypoints = new HashSet<Paypoint>();
        }
    
        public int District_Id { get; set; }
        public int Province_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual Province Province { get; set; }
        public virtual ICollection<Paypoint> Paypoints { get; set; }
    }
}
