//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDIIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Districts = new HashSet<District>();
        }
    
        public int Province_Id { get; set; }
        public int Country_Id { get; set; }
        public string Description { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<District> Districts { get; set; }
    }
}
