//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDIIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Employees = new HashSet<Employee>();
            this.Groups = new HashSet<Group>();
            this.Roles = new HashSet<Role>();
        }
    
        public int User_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Initials { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Date_Last_Login { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
